# spec_version: v1
# kind: langfuse
# project_id: predictive-maintenance-fleet
# api_key: "sk-lf-00000-00000-00000-00000-00000"
# url: "https://cloud.langfuse.com/api/public/otel"
# host_health_uri: "https://cloud.langfuse.com"
# config_json:
#   public_key: "pk-lf-00000-00000-00000-00000-00000"
# mask_pii: false

spec_version: v1
kind: langfuse
project_id: predictive-maintenance-fleet
api_key: "sk-lf-3bac9992-900e-47db-9ac6-35f6fb894300"
url: "https://cloud.langfuse.com/api/public/otel"
host_health_uri: "https://cloud.langfuse.com"
config_json:
  public_key: "pk-lf-3246852b-dd57-4ed8-995d-e70f223b2072"
mask_pii: false
